# Server
server.port=8081
spring.application.name=product-service

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/shopflow_products
spring.datasource.username=root
spring.datasource.password=shopflow123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=shopflow_jwt_super_secret_key_2026
jwt.expiration=900000

# Logging
logging.level.root=INFO
logging.level.com.shopflow=DEBUG
logging.file.name=logs/product-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n